FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/utilities/encodefile
RUN g++ -o encodefile -O3 encodefile.cxx

FROM ubuntu:22.04 as package
COPY --from=builder /repo/utilities/encodefile/encodefile /
